### ISSUE TITLE
Receiver station code required when specified as coordinates

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#22]
There has been a change in your middleware that makes the station code required when passing receiver coordinates. This makes it more cumbersome to use when just wanting to request seismograms for various epicentral distances for example to gain a visual understanding of something.

I think the default `SYN` code is a good enough hint for users. Even the source mechanism has a default value so I think the station code should definitely have one. What is the motivation behind this change? 

Example query: 

http://service.iris.edu/irisws/syngine/1/query?starttime=1969-12-31T23%3A57%3A06.926082Z&dt=24.724845445855724&sourcelongitude=3.0&format=miniseed&receiverlatitude=10.066021190034876&origintime=1970-01-01T00%3A00%3A00.000000Z&components=ZNERT&model=test&sourcelatitude=4.026869595871933&sourcemomenttensor=4.71e%2B17%2C3.81e%2B17%2C-4.74e%2B17%2C3.99e%2B17%2C-8.05e%2B17%2C-1.23e%2B17&receiverlongitude=20.0&sourcedepthinmeters=0.0&units=displacement

**Comment by CTrabant** [comment]
The problem is that specifying more than one receiver with no identifier to disambiguate the the time series results in apparently duplicate data.  Specifically, for the N.S.L.C identifiers in miniSEED and SAC and the file names in the ZIP archive, specifying only receiver coordinates results in using the default identifiers for every seismogram: XX.SYN.SE.?X?

The cumbersome-ness of needing to specify a code is small compared to wanting to unzip an archive of 100s of seismograms with the same file names.  For miniSEED its even worse, you can never tell which receiver is which.

**Comment by krischer** [comment]
Ah I see. I did not consider the bulk requests.

I think the best way to proceed would be to require it for the POST bulk requests but make it optional for the normal GET requests. One of the reasons for the default source was to have kind of a rich man's TauP alternative to quickly calculate synthetics - that would then still be possible.

**Comment by CTrabant** [comment]
True.  Let me work on your suggestion, should be possible and then we can retain the usefulness of all defaults.

**Comment by alexhutko** [comment]
OK.  default stationcode=SYN when receiver lat/lon are given was no bueno.  So default now will be S0001 for single receiver requests and S####, with leading zeros for multiple receiver requests.

**Comment by krischer** [comment]
Great solution!
