### ISSUE TITLE
Bug report: wrong head parameter in sac file

### ISSUE THREAD

**Issue by wangliang1989** [iris-edu/irisws-syngine#38]
if url is http://service.iris.edu/irisws/syngine/1/query?origintime=2017-04-15T06:30:00.000\&sourcelatitude=0\&sourcelongitude=100\&sourcedepthinmeters=20000\&sourcemomenttensor=1.04e22,-0.039e22,-1e22,0.304e22,-1.52,-0.119e22\&receiverlatitude=0\&components=ZRT\&format=saczip\&model=prem_i_2s\&units=velocity\&receiverlongitude=105
, the head parameter of dist should be about 556.599. But, the fact is 20004.3

**Comment by manoch-iris** [comment]
Thank you for reporting. We have confirmed this issue and also found out that if we change lat values to a non-zero value (for example 0.1), DIST field is populated correctly. The issue appears to happen when both lat values are set to zero. Ticket 55 has been opened under Instaseis

**Comment by krischer** [comment]
Fixed in https://github.com/krischer/instaseis/pull/57.

You can fix this by just installing `geographiclib`. The vincenty formula `ObsPy` uses to calculate distances on ellipsoids in unstable in certain special cases. If `geographiclib` is available `ObsPy` will use and their more sophisticated calculations are always stable. The linked PR just makes `geographiclib` a hard dependency and adds a test.

**Comment by manoch-iris** [comment]
Syngine is upgraded to instaseis 1.2.0 and DIST field is populated correctly.
